name: homebridge-nxtlevel

on:
  push:
    branches:
      - master

jobs:
    release:
        name: homebridge-nxtlevel
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: node
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/
            - name: homebridge-nxtlevel
              run: npm publish --access public
              env:
                NODE_AUTH_TOKEN:${{secrets.npm_token}}
